version: "3"
services:
  api-service:
    build: .
    depends_on:
      -db
  db:
    image: "microsoft/mssql-server-linux"
    ports:
          -"1433:1433"
    environment:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"
  nginx-service:
    build:
          context: .
          dockerfile: Dockerfile-Nginx
    ports:
        -"8080:80"
    depends_on:
        - api-service

          